fetch_yahoo_data:
  name: fetch_yahoo_data
  import_path: acme_prefect.flows.fetch_yahoo_data:main
  cron: "0 12 * * 1-5"
  description: Fetches Yahoo Finance data with minute-level granularity
  work_pool_name: ecs-pool

hello_dw:
  name: hello_dw
  import_path: acme_prefect.flows.hello_dw:main
  cron: "0 12 * * 1-5"
  description: Hello DW
  work_pool_name: ecs-pool

hello_world:
  name: hello_world
  import_path: acme_prefect.flows.hello_world:hello_world
  cron: "0 12 * * 1-5"
  description: Hello World
  work_pool_name: ecs-pool
