site_name: acme-prefect
theme:
  name: material # readthedocs
nav:
  - Introduction: index.md
  - Features: features.md
  - Installation: install.md
  - User Guides: guides.md
  - API Reference: api.md
  - Release Notes: release_notes.md
extra_css:
  - stylesheets/extra.css

plugins:
- mkdocstrings