name: Build and Push Docker Image

env:
  IMAGE_NAME: acme-prefect
  REGISTRY: ghcr.io

on:
  workflow_run:
    workflows: ["Run Unit Tests - CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get commit hash
        id: get-commit-hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # NOTE: other tags can be added to the image
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        env:
          COMMIT_HASH: ${{ steps.get-commit-hash.outputs.COMMIT_HASH }}
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,suffix=-latest,event=branch
            type=ref,suffix=-${{ env.COMMIT_HASH }},event=branch
            type=pep440,pattern={{version}},suffix=-${{ env.COMMIT_HASH }} # human readable version
      
      - name: Build & Push Docker image
        id: build-docker-image
        uses: docker/build-push-action@v6
        with:
          context: . # context for env.IMAGE_NAME is currently root dir of the repo, but this will change if multiple projects are in the repo
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            type=gha
            type=registry,ref=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:main-latest
          cache-to: type=gha,mode=max