name: Build and Push Docker Image
# Check https://github.com/PrefectHQ/cicd-example-workspaces

env:
  PROJECT_NAME: acme_prefect
  REGISTRY: ghcr.io

on:
  push:
    # Trigger on push to main branch that modifies the paths as well when specific tag is pushed
    branches:
      - main
    paths:
      - "Dockerfile"
      - ".dockerignore"
      - "uv.lock"
      - "pyproject.toml"
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Get version from branch name
      - name: Get branch name as VERSION when run on branch
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          VERSION=${GITHUB_REF#refs/heads/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version found: $VERSION"
      
      # Get version from tag name
      - name: Get semantic version as VERSION when run from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version found: $VERSION"
      
      - name: Get commit hash
        id: get-commit-hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # TODO: may use docker/metadata-action to create tags
      - name: Build & Push Docker image
        id: build-docker-image
        env:
            GITHUB_SHA: ${{ steps.get-commit-hash.outputs.COMMIT_HASH }}
            VERSION: ${{ env.VERSION }}
        uses: docker/build-push-action@v6
        with:
          context: . # context for env.PROJECT_NAME is root dir of the repo, but this can be changed if multiple projects are in the repo
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:${{ env.VERSION }}-${{ env.GITHUB_SHA }},${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:${{ env.VERSION }}-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max