name: Deploy Prefect flows to DEV
# Check https://github.com/PrefectHQ/cicd-example-workspaces
# https://docs.prefect.io/v3/deploy/infrastructure-concepts/deploy-ci-cd
# https://docs.prefect.io/v3/deploy/infrastructure-concepts/deploy-via-python

env:
  PACKAGE_NAME: acme_prefect
  IMAGE_NAME: acme-prefect
  REGISTRY: ghcr.io
  ENV_LABEL: dev

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
  # push:
  #   branches:
  #     - main
  # schedule: # runs on schedule from main branch to limit the number of deployments
  #   - cron: '0 4 * * *'  # Runs at 4 AM UTC every day
  workflow_dispatch: # allows manual deployments
    inputs:
      flow_name:
        description: 'Flow name to deploy (default: all flows)'
        required: false
        default: 'all'
        type: string

jobs:
  deploy-production:
    name: Deploy to Prefect workspace
    environment: deploy-prefect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Install project
        run: uv sync --all-extras --dev
      
      - name: Get package version number
        id: get-package-version-number
        run: |
          PACKAGE_VERSION=$(uv pip show $PACKAGE_NAME | grep "Version:" | sed 's/Version: //')
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
      
      - name: Get commit hash
        id: get-commit-hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      
      - name: Get image URI Prefix
        id: get-image-uri-prefix
        run: |
          IMAGE_URI_PREFIX=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          echo "IMAGE_URI_PREFIX=$IMAGE_URI_PREFIX" >> "$GITHUB_OUTPUT"
      
      - name: Get branch name when run on branch
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Branch name found: $BRANCH_NAME"
    
      - name: Assume branch name when run from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          BRANCH_NAME=main
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Assumed branch name: $BRANCH_NAME"
      
      ## The below section shows how tag could be selected from tags generated 
      ## by docker/metadata-action@v5 that is used in the build job.
      ## However this method repeats the steps of the build job and 
      ## only uses a heuristic to find the immutable tag. Better way
      ## would be for build job to publish the single right tag so this workflow can access it,
      ## but artifacts are only available within the same workflow run.
      ## TODO: This can perhaps be done with acme-config to publish the tag for the build job and read it from there.

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   env:
      #     COMMIT_HASH: ${{ steps.get-commit-hash.outputs.COMMIT_HASH }}
      #     IMAGE_URI_PREFIX: ${{ steps.get-image-uri-prefix.outputs.IMAGE_URI_PREFIX }}
      #   with:
      #     images: ${{ env.IMAGE_URI_PREFIX }}
      #     tags: |
      #       type=ref,suffix=-latest,event=branch
      #       type=ref,suffix=-${{ env.COMMIT_HASH }},event=branch
      #       type=pep440,pattern={{version}},suffix=-${{ env.COMMIT_HASH }} # human readable version

      # - name: Create Get Image URI Python script
      #   run: |
      #     echo '
      #     import os
      #     tags = os.environ["TAGS"].split(",")
      #     IMAGE_URI_PREFIX = os.environ["IMAGE_URI_PREFIX"]
      #     non_latest = [tag for tag in tags if not tag.endswith("-latest")]
      #     assert len(non_latest) > 0, "No non-latest tags found"
      #     selected_tag = non_latest[0]
      #     print(f"IMAGE_URI={IMAGE_URI_PREFIX}:{selected_tag}")
      #     ' > select_tag.py

      # - name: Get Image URI
      #   id: get-image-uri
      #   env:
      #     IMAGE_URI_PREFIX: ${{ steps.get-image-uri-prefix.outputs.IMAGE_URI_PREFIX }}
      #     TAGS: ${{ steps.meta.outputs.tags }}
      #   run: python3 select_tag.py >> "$GITHUB_OUTPUT"
      
      # Manually recreate the image uri.
      - name: Get Image URI
        id: get-image-uri
        env:
          IMAGE_URI_PREFIX: ${{ steps.get-image-uri-prefix.outputs.IMAGE_URI_PREFIX }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          COMMIT_HASH: ${{ steps.get-commit-hash.outputs.COMMIT_HASH }}
        run: |
          echo "IMAGE_URI=$IMAGE_URI_PREFIX:$BRANCH_NAME-$COMMIT_HASH" >> "$GITHUB_OUTPUT"
      
      # TODO: use temp creds: https://github.com/aws-actions/configure-aws-credentials?tab=readme-ov-file#oidc
      - name: Get default env version number from acme-config
        id: get-default-version-number
        env:
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          ENV_LABEL: ${{ env.ENV_LABEL }}
        run: |
          ENV_VERSION_NUMBER=$(uv run ac get-version -app-name $PACKAGE_NAME -env $ENV_LABEL)
          echo "ENV_VERSION_NUMBER=$ENV_VERSION_NUMBER" >> "$GITHUB_OUTPUT"
      
      - name: Get env config from acme-config
        id: get-env-config
        env:
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          ENV_LABEL: ${{ env.ENV_LABEL }}
          ENV_VERSION_NUMBER: ${{ steps.get-default-version-number.outputs.ENV_VERSION_NUMBER }}
        run: |
          uv run ac fetch -app-name $PACKAGE_NAME -env $ENV_LABEL -ver-number $ENV_VERSION_NUMBER
      
      - name: Prefect Deploy
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
          IMAGE_URI: ${{ steps.get-image-uri.outputs.IMAGE_URI }}
          ENV_VERSION_NUMBER: ${{ steps.get-default-version-number.outputs.ENV_VERSION_NUMBER }}
          ENV_LABEL: ${{ env.ENV_LABEL }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
          COMMIT_HASH: ${{ steps.get-commit-hash.outputs.COMMIT_HASH }}
          PACKAGE_VERSION: ${{ steps.get-package-version-number.outputs.PACKAGE_VERSION }}
        run: |
          uv run prefect cloud workspace set -w ${{ secrets.PREFECT_WORKSPACE }}
          uv run python src/$PACKAGE_NAME/prefect_deploy.py -app-name $PACKAGE_NAME \
           -env $ENV_LABEL -ver-number $ENV_VERSION_NUMBER -image-uri $IMAGE_URI \
           -branch-name $BRANCH_NAME -commit-hash $COMMIT_HASH -project-name $PACKAGE_NAME \
           -package-version $PACKAGE_VERSION --flows-to-deploy ${{ inputs.flow_name || 'all' }}