name: Promote deployment from X to Y

env:
  PACKAGE_NAME: acme_prefect

on:
  workflow_dispatch:
    inputs:
      source-env:
        description: 'Source environment (e.g. dev, tst)'
        required: false
        default: 'dev'
      target-env:
        description: 'Target environment (e.g. tst, prd)'
        required: false
        default: 'tst'
      flows-to-deploy:
        description: 'Comma separated list of flow names to deploy (default: all flows)'
        required: false
        default: 'all'
        type: string

jobs:
  deploy-from-env-to-env:
    name: Deploy from X namespace to Y
    environment: deploy-prefect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name when run on branch
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Branch name found: $BRANCH_NAME"
    
      - name: Assume branch name when run from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          BRANCH_NAME=main
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Assumed branch name: $BRANCH_NAME"
    
      # TODO: use temp creds: https://github.com/aws-actions/configure-aws-credentials?tab=readme-ov-file#oidc
      - name: Get default env version number from acme-config
        id: get-default-version-number
        env:
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          ENV_LABEL: ${{ inputs.target-env }}
        run: |
          ENV_VERSION_NUMBER=$(uv run ac get-version -app-name $PACKAGE_NAME -env $ENV_LABEL)
          echo "ENV_VERSION_NUMBER=$ENV_VERSION_NUMBER" >> "$GITHUB_OUTPUT"
  
      - name: Get env config from acme-config
        id: get-env-config
        env:
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          ENV_LABEL: ${{ inputs.target-env }}
          ENV_VERSION_NUMBER: ${{ steps.get-default-version-number.outputs.ENV_VERSION_NUMBER }}
        run: |
          uv run ac fetch -app-name $PACKAGE_NAME -env $ENV_LABEL -ver-number $ENV_VERSION_NUMBER

      - name: Prefect Deploy via Promotion
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
          ENV_VERSION_NUMBER: ${{ steps.get-default-version-number.outputs.ENV_VERSION_NUMBER }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
        run: |
          uv run prefect cloud workspace set -w ${{ secrets.PREFECT_WORKSPACE }}
          uv run python src/$PACKAGE_NAME/prefect_deploy.py promote -app-name $PACKAGE_NAME \
           -env ${{ inputs.target-env }} -ver-number $ENV_VERSION_NUMBER \
           -branch-name $BRANCH_NAME -project-name $PACKAGE_NAME \
           -source-env ${{ inputs.source-env }} \
           --flows-to-deploy ${{ inputs.flows-to-deploy }}
                